version: "3"
services:
  www:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./webroot:/srv/users/apps/
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - wordpress
    environment:
      - NGINX_HOST=${DOCKER_NGINX_HOST}
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  wordpress:
    image: bitnami/php-fpm:latest
    expose:
      - 9000
    volumes:
      - ./webroot:/srv/users/apps/
      - ./webroot:/etc/nginx/conf.d
      
  database:
    image: mysql:latest
    command: ['--default-authentication-plugin=mysql_native_password']
    ports:
      - 3306:3306
    volumes:
      - database_storage:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=${DOCKER_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_ROOT_PASS}
      - MYSQL_USER=${DOCKER_DB_USER}
      - MYSQL_PASSWORD=${DOCKER_DB_PASS}

volumes:
  database_storage:
    
